### ISSUE TITLE
PSR2 and documentation.

### ISSUE THREAD

**Issue by bar** [wa0x6e/ResqueStatus#1]
1. Is it ok for the lib to use `PSR2` and `CakeResque` not?¿
2. Does docblocks need to be indented?
3. Can I remove the extra spaces from the docs?

Thanks.

**Comment by wa0x6e** [comment]
1. Yes, CakeResque is not using PSR2 because CakePHP does not use it
2. Yes, no docblock indentation is a CakePHP thing
3. What extra space ?

**Comment by bar** [comment]
1. I thought [PSR2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) didn't specify comments or dockblocks.
2. I meant all the multiple tabs and spaces between words [inside the dockblocks](https://github.com/kamisama/ResqueStatus/blob/master/src/ResqueStatus/ResqueStatus.php#L60-L64)

**Comment by wa0x6e** [comment]
1. I've always seen indented docblock, but in CakePHP. I'm following the PEAR convention for the docblock: http://pear.php.net/manual/en/standards.sample.php
2. Yes, they can be removed

**Comment by bar** [comment]
Perfect.
